name: deploy
on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.17"
      - run: npm install
      - run: npm run build
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_SENDER_ID: ${{ secrets.FIREBASE_SENDER_ID}}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_API_KEY: ${{ secrets.STRAVA_API_KEY }}
      - run: cp docs/index.html docs/404.html
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
